
spring:
  profiles:
    #active: dev This means it will use the application-dev.yml file. You'll see this "The following 1 profile is active: "dev"" to the console on running the application

# You can do the same for prod. You'll see this "The following 1 profile is active: "prod"" to the console on running the application
#spring:
  #profiles:
    #active: prod

# To make the switch of profiles more dynamic we can do this. You have to define the <profiles></profiles> in the pom.xml file
    #spring:
    #profiles:
    active: @spring.profiles.active@ #This is a global property that we shall use in the pom.xml file in the <properties></properties> configuration of the profiles